---
title: "Fragments"
author: "Philippe MICHEL"
lang: fr
language: 
  title-block-author-single: "Auteur"
format: 
  html:
    highlight-style: ayu-light
include-in-header:
   text: |
eval: true
echo: true
---

```{r}
#| label: setup

library(tidyverse)
library(baseph)
library(gtsummary)
library(ggsci)
#
names(patients)[1] <- "sexe"
```

# R

## Graphiques

### Mise en forme

Mise en forme d'un graphique `ggplot2`. 

```{r}
#| label: graphique

patients |> 
  ggplot() +
  aes(x = age, fill = lieudevie1) +
  geom_histogram(binwidth = 10, position = "dodge") +

# Snippet : stgraph

labs(title = "",
    subtitle = "",
    x = "",
    y = "",
    caption = "",
    fill = "") +
theme_light() +
scale_fill_jama() +
theme(
  plot.title = element_text(size = 14, face = "bold"),
  plot.subtitle = element_text(size = 12),
  axis.title.x = element_text(size = 12),
  legend.title = element_text(size = 12),
  axis.title.y = element_text(
    size = 12,
    angle = 0,
    vjust = .5
  ),
axis.text.x = element_text(size = 12),
axis.text.y = element_text(size = 12),
legend.position = "right"
)
```

### Pyramide des âges
```{r}
#| label: Pyramide des âges

# Adapter les breaks & les labels.

library(apyramid)
#
patients |> 
  mutate(agerec = cut(age,
    breaks = c(20, 30, 40, 50, 60, 70, 80, 90, 100),
    labels = c("21-30", "31,40", "41-50", "51-60", "61-70", "71,80", "81-90", ">90")
))|>
mutate(agerec = as.factor(agerec)) |>
# Tracé du graphique
age_pyramid(age_group = "agerec",
            split_by = "sexe",
            pal = c("pink", "lightblue"),
show_midpoint = FALSE) +
theme_light() +
    labs(title = "Pyramide des âges",
         y = "ans",
        fill = "Sexe") + 
    theme(
      plot.title = element_text(size = 14, face = "bold"),
      plot.subtitle = element_text(size = 12),
      axis.title.x = element_blank(),
      axis.title.y = element_text(size = 12),
      legend.title = element_blank(),
      legend.position = "bottom")
```


# Quarto


# Colonnes dans une diapo

```{r}
#| label: colonnes 
#| eval: false

# Colonnes pour une présentation (diapo)

:::: {.columns}

::: {.column width="40%"}
Bla bla de gauche
:::

::: {.column width="60%"}
Bla bla de droite
:::

::::
```





